/**
 * Supabase Database Type Definitions
 *
 * This file will be auto-generated by Supabase CLI in production.
 * For now, we manually define the schema types.
 *
 * To auto-generate in the future, run:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts
 */

import type { RoomStatus, TicketGrid } from './loto';

export interface Database {
  public: {
    Tables: {
      rooms: {
        Row: {
          id: string;
          room_code: string;
          host_id: string;
          status: RoomStatus;
          created_at: string;
          started_at: string | null;
          ended_at: string | null;
        };
        Insert: {
          id?: string;
          room_code: string;
          host_id: string;
          status?: RoomStatus;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
        Update: {
          id?: string;
          room_code?: string;
          host_id?: string;
          status?: RoomStatus;
          created_at?: string;
          started_at?: string | null;
          ended_at?: string | null;
        };
      };
      tickets: {
        Row: {
          id: string;
          room_id: string;
          player_id: string;
          player_name: string | null;
          ticket_data: TicketGrid;
          ticket_hash: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          player_id: string;
          player_name?: string | null;
          ticket_data: TicketGrid;
          ticket_hash: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          player_id?: string;
          player_name?: string | null;
          ticket_data?: TicketGrid;
          ticket_hash?: string;
          created_at?: string;
        };
      };
      called_numbers: {
        Row: {
          id: string;
          room_id: string;
          number: number;
          called_at: string;
          called_by: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          number: number;
          called_at?: string;
          called_by: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          number?: number;
          called_at?: string;
          called_by?: string;
        };
      };
    };
  };
}
